CREATE TABLE "approvals" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"space_id" integer NOT NULL,
	"story_id" bigint NOT NULL,
	"approver_id" bigint NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "comments" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"discussion_id" bigint NOT NULL,
	"space_id" integer NOT NULL,
	"user_id" bigint,
	"message" text,
	"message_json" json DEFAULT '[]'::json NOT NULL,
	"uuid" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "comments_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE TABLE "discussions" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"space_id" integer NOT NULL,
	"story_id" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "workflow_stage_changes" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"space_id" integer NOT NULL,
	"story_id" bigint NOT NULL,
	"workflow_stage_id" integer NOT NULL,
	"user_id" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "branches" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "branches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_space_id_spaces_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."spaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_discussion_id_discussions_id_fk" FOREIGN KEY ("discussion_id") REFERENCES "public"."discussions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_space_id_spaces_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."spaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discussions" ADD CONSTRAINT "discussions_space_id_spaces_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."spaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workflow_stage_changes" ADD CONSTRAINT "workflow_stage_changes_space_id_spaces_id_fk" FOREIGN KEY ("space_id") REFERENCES "public"."spaces"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_approvals_space_id" ON "approvals" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "idx_comments_discussion_id" ON "comments" USING btree ("discussion_id");--> statement-breakpoint
CREATE INDEX "idx_comments_space_id" ON "comments" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "idx_discussions_space_id" ON "discussions" USING btree ("space_id");--> statement-breakpoint
CREATE INDEX "idx_workflow_stage_changes_space_id" ON "workflow_stage_changes" USING btree ("space_id");